### ISSUE TITLE
Add more content to instance cards

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#16]
The cards in the grid view should contain more information below the image for more attractive filtering.

**Comment by atrieder** [comment]
Adding an update to this issue since a lot of things were changed in the project code:
 - We have added tooltips to all cards to provide general, at-a-glance information to users.
 - Titles are rendered above the cards at all times to help users more easily identify the instances.
 - A potential area where we may put data that should always be visible is the gray area at the bottom of the cards.
