### ISSUE TITLE
As a user, I would like to see a navigation bar with icons. This would help make the site more appealing.

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#37]
Time Estimation: 1 hour
Assumption: Icon images are freely sourced
Actual Time: 2 weeks

**Comment by mitchellmarshe** [comment]
Implementing navigation icons took a lot of time because React-Bootstrap3 is quite strict when modifying their code with overlays. Andrew and I discovered that React-Bootstrap3 doesn't support flex boxes which allows for alignment of objects. Thus, our icons sit towards the left of the text that describes them. Originally we wanted the icons to sit above the text, but then the hamburger or mobile menu rendered itself in an ugly fashion.

**Comment by atrieder** [comment]
While it may be difficult to choose icons that are both immediately identifiable by the user and representative of the content, I think that having icons to complement the navigation bar labels may still yield some benefit. The icons may be highlighted more than the text so that the user might initially rely on them to determine each category, while the label text remains to clear possible confusion. Examples of this idea is mentioned here: http://thekineticui.com/mobile-navigation-design-fundamentals/

So far, the latest layout that seems to work (displays well in the hamburger menu) is as follows:
 - Icons and labels are presented on the same line
 - Icons are followed by labels to the right
 - Both the labels and icons are of a similar height
