### ISSUE TITLE
As a user, I'd like to see the items to be aligned in a grid, either in the center two spots or the left 2 spots.

### ISSUE THREAD

**Issue by ChiaHuaLu** [cilki/gameframe.online#63]
<img width="955" alt="gameframe" src="https://user-images.githubusercontent.com/15913503/38523320-b6496424-3c10-11e8-95dc-bcd13a5f4f63.png">

**Comment by atrieder** [comment]
Since commit 32e795a8503f2ef0b1a9c7ba8982656dfc1641be, the grid cards are now centered such that the spacing between them does not deviate at the bottom row. Combined with the recent changes to the number of cards displayed on each page, the positioning of the cards adheres to the perceived "grid lines" implied by the inter-card spacing.

![dank](https://user-images.githubusercontent.com/21695410/38655509-b5996116-3dda-11e8-9a57-11d46d818e06.png)

Based on the above mentioned changes, this user story appears to be complete

**Comment by mitchellmarshe** [comment]
Estimated Time: 1 hour
Actual Time: 1 hour
