### ISSUE TITLE
As a user, it would be nice if the filters that have no items in them get removed

### ISSUE THREAD

**Issue by ccmmaa** [cilki/gameframe.online#67]
![screen shot 2018-04-09 at 4 19 39 pm](https://user-images.githubusercontent.com/14240251/38523752-1b878cfc-3c12-11e8-987a-bddc1f3abaf2.png)
For example, there are no developers in Angola

**Comment by cilki** [comment]
While this seems like a good idea, some people may wonder where their favorite country, Angola, is on the filter list. It's more intuitive for the filter to return no results than for the filter to simply not exist. The same goes for platforms and genres.

**Comment by therealsamf** [comment]
I agree with @cilki, we don't want to be discriminatory towards specific countries and/or platforms, genres, and the like. Also, each filter would require a large request to our database of rapidly changing data. What's empty today may not be empty tomorrow

**Comment by atrieder** [comment]
I think that we might be able to improve the usability of our website by adding a message to indicate when there are no instances to be displayed for the given filter. That way, the page would at least let the user know that there is nothing to be shown (since a blank page might be interpreted as unintentional otherwise).

**Comment by atrieder** [comment]
In commit b7e0f740c251fd319e06e3369bb7fb19044fc1c4, a message is now displayed to inform the user that there are no instances to be displayed:

![SCRNSHOT](https://user-images.githubusercontent.com/21695410/38950926-9a174a3e-430c-11e8-9c0e-06ae63bc345b.png)

Since the functionality outlined in my previous comment is now implemented, I think that this user story is complete.

**Comment by mitchellmarshe** [comment]
Estimated Time: 20 min
Actual Time: 10 min
