### ISSUE TITLE
As a user, I would like to figure out what the media at the bottom of the game instances when hovered over means

### ISSUE THREAD

**Issue by ccmmaa** [cilki/gameframe.online#71]
![screen shot 2018-04-09 at 4 36 25 pm](https://user-images.githubusercontent.com/14240251/38524484-5a15c28e-3c14-11e8-805b-923f1e989d9f.png)
The instance either looked like the one in the picture with nothing next to or below Media or below Media was the word "None." I am not sure what is supposed to be there or if anything is supposed to be there.

**Comment by mitchellmarshe** [comment]
![image](https://user-images.githubusercontent.com/31491237/38576292-59250bfa-3cc3-11e8-83f0-698ca4f9af15.png)

Thanks for pointing this out to me, ccmmaa.

I've redeveloped the information on the backside of the cards entirely. You'll notice the changes in the picture above. Now there is appropriate scaling of information and information only shows up if its given as a prop. The media field is there to show external sources of information, i.e., links. However, I have not been able to make the link work since the <a> is nested. So this feature might disappear as the instance pages of each card contains an appropiate link. Furthermore, the usage of the information on the backside of the card is meant for searching, sorting, and filtering.

**Comment by mitchellmarshe** [comment]
This user story is estimated to take 1 hour. The actual time it took to complete this story is 4 hours because of all other features needed to project information on the backside of a card.
