### ISSUE TITLE
Long developer logos extend off screen

### ISSUE THREAD

**Issue by cilki** [cilki/gameframe.online#85]
The developer logo needs to be capped at 100% the width of the page.

Developer 13165 is a good example of this.

**Comment by atrieder** [comment]
I have been able to reproduce this issue. It seems to be because I currently size the logos based on their height (horizontal logos get scaled more than vertical or square logos).

**Comment by cilki** [comment]
@atrieder Did you look at the instance page for developer 13165? For me the logo extends off the screen.

**Comment by atrieder** [comment]
@cilki No, I looked at developer 29 on our production database (Square Enix, which is accessible from the first page of the developer grid by default). On my machine, the browser window has to be very large to fit the whole logo on the Jumbotron element. I can't seem to access 13165 right now, but I think that the issue is the same.

The solution seems to just be to cap the max width of the logo, rather than blindly resizing it to a certain height

**Comment by atrieder** [comment]
I think that I fixed the issue in 02f4e99a056490795af9b4b8c08cdd9fd824a28b (Logos are scaled until their height OR width reaches a certain amount, but width is considered over height).

This seems to work for developer 13165.
